let stocks = [];
let view = localStorage.getItem('jse-main-view') || 'table';
let activeTab = localStorage.getItem('jse-main-tab') || 'overview';

const $ = id => document.getElementById(id);
const fmt = (v,d=2) => v == null || Number.isNaN(Number(v)) ? 'N/A' : Number(v).toFixed(d);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unit = x => x.currency === 'USD' ? 'US$' : 'J$';
const directJse = x => typeof x?.jseUrl === 'string' && /^https:\/\/www\.jamstockex\.com\/trading\/instruments\/\?instrument=\d+$/.test(x.jseUrl) ? x.jseUrl : null;
const saUrl = x => x?.saUrl || `https://stockanalysis.com/quote/${String(x?.saMarket || 'jmse').toLowerCase()}/${encodeURIComponent(x?.saTicker || x?.ticker || '')}/`;

function sourceName(x,key,fallback='') { return String(x?.[`${key}Source`] || fallback).toUpperCase(); }
function src(label,title,url) {
  const cls = label.toLowerCase().replace(/\s+/g,'-');
  return url ? `<a class="src ${cls}" href="${url}" target="_blank" rel="noopener" title="${esc(title)}">${esc(label)}</a>` : `<span class="src ${cls}" title="${esc(title)}">${esc(label)}</span>`;
}
function metricBadge(x,key,fallback='CALC') {
  const s = sourceName(x,key,fallback);
  if (s.startsWith('SA')) return src(s.includes('TTSE')?'SA TTSE':'SA',`Published by StockAnalysis${s.includes('TTSE')?' TTSE':''}`,saUrl(x));
  if (s === 'JSE') return src('JSE','Official JSE value',directJse(x));
  if (s === 'CALC') return src('CALC','Calculated fallback');
  return s ? src(s,s) : '';
}
function tickerHtml(x){const u=directJse(x);return u?`<a class="ticker" href="${u}" target="_blank" rel="noopener">${esc(x.ticker)} ↗</a>`:`<span class="ticker">${esc(x.ticker)}</span>`;}
function ratingBadge(r){const v=r||'WATCH';return `<span class="rating ${esc(v)}">${esc(v)}</span>`;}
function scoreCell(x){return `<button type="button" class="score-detail-btn compact" data-score-ticker="${esc(x.ticker)}"><strong>${x.score??'N/A'}</strong><span>/100</span><i>ⓘ</i></button>`;}
function statusText(x,key){return x?.metricStatus?.[key]?.state==='error'?'<span class="negative">ERROR</span>':'N/A';}

function row(x){
  const priceBadge=x.price==null?'':((x.priceSource||x.source||'JSE').toUpperCase()==='JSE'?src('JSE','Official JSE closing price',directJse(x)):src('SA','Delayed StockAnalysis price',saUrl(x)));
  return `<tr><td>${tickerHtml(x)}</td><td>${esc(x.company)} <a class="sa-link" href="${saUrl(x)}" target="_blank" rel="noopener">SA↗</a></td><td>${esc(x.sector||'N/A')}</td><td>${esc(x.ratingBasis||'N/A')}</td><td>${x.price==null?'N/A':unit(x)+fmt(x.price)+priceBadge}</td><td>${x.eps==null?statusText(x,'eps'):fmt(x.eps)+metricBadge(x,'eps','SA')}</td><td>${x.pe==null?statusText(x,'pe'):fmt(x.pe)+metricBadge(x,'pe')}</td><td>${x.pb==null?statusText(x,'pb'):fmt(x.pb)+metricBadge(x,'pb')}</td><td class="${x.roe>12?'positive':x.roe!=null&&x.roe<5?'negative':''}">${x.roe==null?statusText(x,'roe'):fmt(x.roe)+'%'+metricBadge(x,'roe','SA')}</td><td class="${x.epsGrowth>0?'positive':x.epsGrowth<0?'negative':''}">${x.epsGrowth==null?statusText(x,'epsGrowth'):fmt(x.epsGrowth)+'%'+metricBadge(x,'epsGrowth','SA')}</td><td>${x.divYield==null?statusText(x,'divYield'):fmt(x.divYield)+'%'+metricBadge(x,'divYield')}</td><td>${esc(x.fairValue||'N/A')}</td><td>${esc(x.buyZone||'N/A')}</td><td>${scoreCell(x)}</td><td>${ratingBadge(x.rating)}</td></tr>`;
}
function card(x){
  return `<article class="stock-card"><div class="stock-head"><div style="min-width:0">${tickerHtml(x)}<div class="company">${esc(x.company)}</div></div><div class="price">${x.price==null?'N/A':unit(x)+fmt(x.price)}</div></div><div class="basis">${esc(x.ratingBasis||'N/A')} • ${esc(x.sector||'N/A')}</div><div class="metric-grid"><div class="metric"><span>EPS</span><strong>${x.eps==null?statusText(x,'eps'):fmt(x.eps)}</strong></div><div class="metric"><span>P/E</span><strong>${x.pe==null?statusText(x,'pe'):fmt(x.pe)}</strong></div><div class="metric"><span>P/B</span><strong>${x.pb==null?statusText(x,'pb'):fmt(x.pb)}</strong></div><div class="metric"><span>ROE</span><strong class="${x.roe>12?'positive':x.roe!=null&&x.roe<5?'negative':''}">${x.roe==null?statusText(x,'roe'):fmt(x.roe)+'%'}</strong></div><div class="metric"><span>EPS Growth</span><strong class="${x.epsGrowth>0?'positive':x.epsGrowth<0?'negative':''}">${x.epsGrowth==null?statusText(x,'epsGrowth'):fmt(x.epsGrowth)+'%'}</strong></div><div class="metric"><span>Yield</span><strong>${x.divYield==null?statusText(x,'divYield'):fmt(x.divYield)+'%'}</strong></div><div class="metric"><span>Score</span>${scoreCell(x)}</div><div class="metric"><span>Rating</span><strong>${ratingBadge(x.rating)}</strong></div></div><div class="range-grid"><div class="range-box"><span>Fair Value</span><strong>${esc(x.fairValue||'N/A')}</strong></div><div class="range-box"><span>Buy Zone</span><strong>${esc(x.buyZone||'N/A')}</strong></div></div><div class="card-footer"><div class="card-actions">${directJse(x)?`<a href="${directJse(x)}" target="_blank" rel="noopener">JSE ↗</a>`:''}<a href="${saUrl(x)}" target="_blank" rel="noopener">SA ↗</a></div>${ratingBadge(x.rating)}</div></article>`;
}
function filtered(){
  const q=($('search')?.value||'').toLowerCase(),r=$('ratingFilter')?.value||'',s=$('sectorFilter')?.value||'';
  const k=$('sortSelect')?.value||'score';
  const a=stocks.filter(x=>(!q||`${x.ticker} ${x.company}`.toLowerCase().includes(q))&&(!r||x.rating===r)&&(!s||x.sector===s));
  a.sort((x,y)=>k==='pb'?(x.pb??999)-(y.pb??999):k==='roe'?(y.roe??-999)-(x.roe??-999):k==='pe'?(x.pe??999)-(y.pe??999):k==='yield'?(y.divYield??-999)-(x.divYield??-999):(y.score??-999)-(x.score??-999));
  return a;
}
function renderKpis(){
  const c={BUY:0,HOLD:0,WATCH:0,AVOID:0};stocks.forEach(x=>{if(c[x.rating]!=null)c[x.rating]++});
  const active=$('ratingFilter')?.value||'ALL';
  const specs=[['Universe',stocks.length,'ALL','universe'],['BUY',c.BUY,'BUY','buy'],['HOLD',c.HOLD,'HOLD','hold'],['WATCH',c.WATCH,'WATCH','watch'],['AVOID',c.AVOID,'AVOID','avoid']];
  const html=specs.map(v=>`<button class="kpi ${v[3]} ${active===v[2]?'active':''}" data-rating="${v[2]}"><span class="label">${v[0]}</span><span class="value">${v[1]}</span></button>`).join('');
  if($('kpis'))$('kpis').innerHTML=html;if($('kpisStocks'))$('kpisStocks').innerHTML=html;
  document.querySelectorAll('.kpi').forEach(b=>b.onclick=()=>{if($('ratingFilter'))$('ratingFilter').value=b.dataset.rating==='ALL'?'':b.dataset.rating;setTab('stocks');renderKpis();renderStocks();});
}
function setView(v){view=v;localStorage.setItem('jse-main-view',v);$('tableViewBtn')?.classList.toggle('active',v==='table');$('cardViewBtn')?.classList.toggle('active',v==='cards');$('tableView')?.classList.toggle('hidden',v!=='table');$('desktopCards')?.classList.toggle('hidden',v!=='cards');}
function renderStocks(){const a=filtered();if($('stockRows'))$('stockRows').innerHTML=a.map(row).join('');if($('desktopCards'))$('desktopCards').innerHTML=a.map(card).join('');if($('mobileList'))$('mobileList').innerHTML=a.map(card).join('');setView(view);}
function rankStocks(mode){const a=[...stocks];if(mode==='dividend')return a.filter(x=>x.divYield!=null).sort((x,y)=>y.divYield-x.divYield).slice(0,10);if(mode==='growth')return a.filter(x=>x.epsGrowth!=null).sort((x,y)=>y.epsGrowth-x.epsGrowth).slice(0,10);if(mode==='value')return a.filter(x=>x.pe>0).sort((x,y)=>x.pe-y.pe).slice(0,10);return a.filter(x=>x.score!=null).sort((x,y)=>y.score-x.score).slice(0,10);}
function rankBlock(title,mode,sub){return `<article class="panel section-card"><p class="eyebrow">${esc(sub)}</p><h2>${esc(title)}</h2><div class="rank-list">${rankStocks(mode).map((x,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div><div class="rank-main"><strong>${esc(x.ticker)} • ${esc(x.company)}</strong><span>${esc(x.ratingBasis||x.sector||'')}</span></div><div class="rank-score">${mode==='dividend'?fmt(x.divYield)+'%':mode==='growth'?fmt(x.epsGrowth)+'%':mode==='value'?fmt(x.pe)+'×':x.score}</div></div>`).join('')}</div></article>`;}
function renderRankings(){if($('rankingsGrid'))$('rankingsGrid').innerHTML=rankBlock('Top Overall','score','Opportunity score')+rankBlock('Dividend Opportunities','dividend','Income')+rankBlock('Growth Opportunities','growth','EPS growth')+rankBlock('Value Stocks','value','Low positive P/E');}
function portfolioSet(type){let pool=stocks.filter(x=>x.rating==='BUY'||x.rating==='HOLD');pool.sort((a,b)=>type==='income'?(b.divYield??-1)-(a.divYield??-1):type==='growth'?(b.epsGrowth??-999)-(a.epsGrowth??-999):(b.score??-999)-(a.score??-999));pool=pool.slice(0,7);const raw=pool.map(x=>type==='income'?Math.max(1,x.divYield||1):type==='growth'?Math.max(1,Math.min(30,(x.epsGrowth||0)+10)):Math.max(1,x.score||1));const total=raw.reduce((a,b)=>a+b,0)||1;const out=pool.map((x,i)=>({x,pct:Math.round(raw[i]/total*100)}));const diff=100-out.reduce((s,o)=>s+o.pct,0);if(out[0])out[0].pct+=diff;return out;}
function portfolioCard(title,type,copy){return `<article class="panel portfolio-card"><p class="eyebrow">Model portfolio</p><h3>${esc(title)}</h3><p class="section-copy">${esc(copy)}</p>${portfolioSet(type).map(o=>`<div class="alloc-row"><div><div class="alloc-label"><span>${esc(o.x.ticker)}</span><span>${ratingBadge(o.x.rating)}</span></div><div class="alloc-track"><div class="alloc-fill" style="width:${o.pct}%"></div></div></div><div class="alloc-pct">${o.pct}%</div></div>`).join('')}</article>`;}
function renderPortfolios(){if($('portfolioGrid'))$('portfolioGrid').innerHTML=portfolioCard('Dividend / Income','income','Prioritizes yield with BUY/HOLD discipline.')+portfolioCard('Growth & Appreciation','growth','Leans toward positive EPS growth while limiting concentration.')+portfolioCard('Balanced Total Return','balanced','Uses the Opportunity Score as the primary allocation signal.');}
const glossary=[['EPS','Earnings Per Share','Net income attributable to ordinary shareholders ÷ weighted-average ordinary shares','Profit earned for each ordinary share.'],['EPS Growth','Earnings growth','(Current EPS ÷ Prior EPS − 1) × 100','Shows the direction and rate of earnings growth.'],['BVPS','Book Value Per Share','Common equity ÷ ordinary shares outstanding','Especially useful for financial and asset-heavy companies.'],['P/B','Price-to-Book','SA published P/B preferred; otherwise JSE close ÷ BVPS','Read together with ROE.'],['P/E','Price-to-Earnings','SA published P/E preferred; otherwise JSE close ÷ EPS','Compare with growth, quality, history and peers.'],['ROE','Return on Equity','Net income ÷ average common equity × 100','Measures profitability on shareholder capital.'],['Dividend Yield','Income yield','SA published yield preferred; otherwise trailing DPS ÷ JSE close × 100','High yield alone does not make a stock attractive.'],['Fair Value','Analyst valuation range','Sector-appropriate normalized valuation methods','Analyst-reviewed valuation range.'],['Buy Zone','Margin-of-safety range','Fair value adjusted for required margin of safety','Preferred entry range.'],['Opportunity Score','Composite score','Valuation 25 + Quality 20 + Growth 20 + Financial Strength 15 + Dividend 10 + Momentum/Catalysts 10','Supports the valuation-aware rating.']];
function renderGlossary(){if($('glossaryGrid'))$('glossaryGrid').innerHTML=glossary.map(g=>`<article class="panel glossary-card"><div class="term">${esc(g[0])}</div><h3>${esc(g[1])}</h3><div class="formula">${esc(g[2])}</div><p class="interpretation">${esc(g[3])}</p></article>`).join('');}
function signalClass(kind,v,x){if(v==null)return'neutral';if(kind==='roe')return v>=15?'good':v>=8?'neutral':'bad';if(kind==='growth')return v>=10?'good':v>=0?'neutral':'bad';if(kind==='yield')return v>=4?'good':v>=2?'neutral':'warn';if(kind==='pe')return v>0&&v<=12?'good':v<=20?'neutral':'warn';if(kind==='pb'){const f=/bank|financial|insurance|investment|real estate|fund/i.test(x.sector||'');return f?(v<=1?'good':v<=1.5?'neutral':'warn'):(v<=2?'neutral':'warn');}return'neutral';}
function caseCard(x){const m=[['P/E',x.pe,'pe',x.pe==null?statusText(x,'pe'):fmt(x.pe)+'×'],['P/B',x.pb,'pb',x.pb==null?statusText(x,'pb'):fmt(x.pb)+'×'],['ROE',x.roe,'roe',x.roe==null?statusText(x,'roe'):fmt(x.roe)+'%'],['EPS Growth',x.epsGrowth,'growth',x.epsGrowth==null?statusText(x,'epsGrowth'):fmt(x.epsGrowth)+'%'],['Yield',x.divYield,'yield',x.divYield==null?statusText(x,'divYield'):fmt(x.divYield)+'%']];return `<article class="panel case-card"><div class="case-head"><div>${tickerHtml(x)}<h3>${esc(x.company)}</h3><small>${esc(x.sector||'')}</small></div>${ratingBadge(x.rating)}</div><p class="case-thesis">${esc(x.ratingBasis||'No rating basis available')}</p><div class="case-metrics">${m.map(z=>`<div class="case-metric ${signalClass(z[2],z[1],x)}"><span>${z[0]}</span><strong>${z[3]}</strong></div>`).join('')}</div><div class="case-footer"><span>Fair Value <strong>${esc(x.fairValue||'N/A')}</strong></span><span>Buy Zone <strong>${esc(x.buyZone||'N/A')}</strong></span><span>Score <strong>${x.score??'N/A'}/100</strong></span></div></article>`;}
function renderRatingCase(){if(!$('ratingCaseGrid'))return;const q=($('caseSearch')?.value||'').toLowerCase(),r=$('caseRating')?.value||'';$('ratingCaseGrid').innerHTML=stocks.filter(x=>(!q||`${x.ticker} ${x.company}`.toLowerCase().includes(q))&&(!r||x.rating===r)).sort((a,b)=>(b.score??-999)-(a.score??-999)).map(caseCard).join('');}
function renderOverview(){if(!$('overviewGrid'))return;const top=[...stocks].filter(x=>x.rating==='BUY').sort((a,b)=>(b.score??-999)-(a.score??-999)).slice(0,5),avoid=[...stocks].filter(x=>x.rating==='AVOID').sort((a,b)=>(a.score??999)-(b.score??999)).slice(0,5);const block=(title,eyebrow,arr)=>`<article class="panel section-card"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><div class="rank-list">${arr.map((x,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div><div class="rank-main"><strong>${esc(x.ticker)} • ${esc(x.company)}</strong><span>${esc(x.ratingBasis||'')}</span></div><div class="rank-score">${x.score}/100</div></div>`).join('')}</div></article>`;$('overviewGrid').innerHTML=block('Highest-ranked BUYs','Current opportunities',top)+block('Lowest-ranked AVOIDs','Risk control',avoid)+`<article class="panel section-card"><p class="eyebrow">Methodology</p><h2>Source hierarchy</h2><p class="section-copy">Official JSE close is authoritative for Jamaica-market price. StockAnalysis-published ratios and fundamentals are preferred. CALC is fallback only.</p></article>`;}
function renderAll(){renderKpis();renderOverview();renderStocks();renderRatingCase();renderRankings();renderPortfolios();renderGlossary();}
function setTab(name){const valid=['overview','stocks','ratingcase','rankings','portfolios','glossary'];if(!valid.includes(name))name='overview';activeTab=name;localStorage.setItem('jse-main-tab',name);document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));}
function showLoadError(e){console.error('Dashboard load failed',e);if($('subtitle'))$('subtitle').textContent='Unable to load dashboard data';if($('updatedPill'))$('updatedPill').textContent='DATA ERROR';if($('overviewGrid'))$('overviewGrid').innerHTML=`<article class="panel section-card"><p class="eyebrow">Data load error</p><h2>Dashboard data could not be loaded</h2><p class="section-copy">${esc(e?.message||String(e))}</p></article>`;}
async function load(){try{const res=await fetch(`./data.json?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`data.json HTTP ${res.status}`);const d=await res.json();if(!Array.isArray(d.stocks))throw new Error('data.json does not contain a stocks array');let base=d.stocks;try{const rr=await fetch(`./research.json?v=${Date.now()}`,{cache:'no-store'});if(rr.ok){const rd=await rr.json(),m=new Map((rd.stocks||[]).map(x=>[x.ticker,x]));base=base.map(x=>m.has(x.ticker)?{...m.get(x.ticker),...x,scoreComponents:x.scoreComponents??m.get(x.ticker).scoreComponents,scoreBreakdown:x.scoreBreakdown??m.get(x.ticker).scoreBreakdown}:x);}}catch(e){console.warn('Research overlay unavailable',e);}stocks=base;const links=stocks.filter(directJse).length,asOf=d.asOf||d.jseTradeDate||'';if($('updatedPill'))$('updatedPill').textContent=asOf?`Market data ${asOf}`:'Latest available data';if($('subtitle'))$('subtitle').textContent=`${stocks.length} ordinary shares • ${links}/${stocks.length} direct JSE instrument links • valuation-aware research`;if($('sectorFilter')){$('sectorFilter').innerHTML='<option value="">All sectors</option>';[...new Set(stocks.map(x=>x.sector).filter(Boolean))].sort().forEach(s=>$('sectorFilter').insertAdjacentHTML('beforeend',`<option>${esc(s)}</option>`));}renderAll();setTab(activeTab);}catch(e){showLoadError(e);}}

document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
['search','ratingFilter','sectorFilter','sortSelect'].forEach(id=>$(id)?.addEventListener(id==='search'?'input':'change',()=>{renderKpis();renderStocks();}));
$('tableViewBtn')?.addEventListener('click',()=>setView('table'));
$('cardViewBtn')?.addEventListener('click',()=>setView('cards'));
$('caseSearch')?.addEventListener('input',renderRatingCase);
$('caseRating')?.addEventListener('change',renderRatingCase);

load();
